// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuuFwjrQBpbmRxZnPHf56_B4tudBEhHx8',
    appId: '1:830264357579:web:bd4e197a3ca60b5740a14e',
    messagingSenderId: '830264357579',
    projectId: 'lokertwincom',
    authDomain: 'lokertwincom.firebaseapp.com',
    storageBucket: 'lokertwincom.appspot.com',
    measurementId: 'G-JX58D1FMSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ksd5LcLur6eI5KndZM0FkQ5qBYcAWt0',
    appId: '1:830264357579:android:783c08391b7d5c5740a14e',
    messagingSenderId: '830264357579',
    projectId: 'lokertwincom',
    storageBucket: 'lokertwincom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLz3c2jCv8GgjrMVYNfvziaiNjM_GogBs',
    appId: '1:830264357579:ios:c12c07e7257386eb40a14e',
    messagingSenderId: '830264357579',
    projectId: 'lokertwincom',
    storageBucket: 'lokertwincom.appspot.com',
    iosClientId: '830264357579-gmv2k2gmlf3ln2dpgobs87aolgvfgp9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.loker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLz3c2jCv8GgjrMVYNfvziaiNjM_GogBs',
    appId: '1:830264357579:ios:c12c07e7257386eb40a14e',
    messagingSenderId: '830264357579',
    projectId: 'lokertwincom',
    storageBucket: 'lokertwincom.appspot.com',
    iosClientId: '830264357579-gmv2k2gmlf3ln2dpgobs87aolgvfgp9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.loker',
  );
}
